In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.6'

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
# how to convert list to array
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(type(my_list))   # in oops class are divided in to two part in build and user defined(these are inbuild class)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [11]:
np.arange(20,10) # first arg<2nd arg then only it is valid

array([], dtype=int64)

In [12]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [13]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
np.zeros(5) #PARAMETER TUNING one dimension array (only one row) here we got float

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5,dtype=int) #convert float to int HYPERPARAMETER TUNING

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((2,2))    #2 dimension (parameter tuning)

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros((2,3),dtype=int)       # 2 dimension (hyperparameter tuning)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros((10,3),dtype=int)   

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.zeros((10,10),dtype=int) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(4) #parameter every time float value

array([1., 1., 1., 1.])

In [23]:
np.ones((2,3),dtype=int) #hyperparameter tuning

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
np.two((2,3))  #two is not the functionality of numpy

AttributeError: module 'numpy' has no attribute 'two'

In [25]:
np.three((2,3))   # not functionality of numpy

AttributeError: module 'numpy' has no attribute 'three'

In [27]:
#generating otp with help of numpy
rand(2,3)

NameError: name 'rand' is not defined

In [28]:
random.rand(2,3)

NameError: name 'random' is not defined

In [31]:
np.random.rand(2)  #two random numbers are generating(every time you run the code u get random dif numbers)

array([0.47278083, 0.29267118])

In [36]:
np.random.rand(2,3) #all numbers are in float

array([[0.81490645, 0.54482166, 0.84635605],
       [0.49991751, 0.25582828, 0.99270461]])

In [44]:
np.random.randint(2)# it will generate random integer value  between 0 to 2

1

In [45]:
np.random.randint(2,9) # every time run new value displays between 2 to 9

5

In [46]:
np.random.randint(2,9,4) #generate random integer between 2-9 where 9 is exclusive(by this we can generate otp)

array([5, 4, 8, 8], dtype=int32)

In [58]:
import numpy as np       #otp generation

otp = np.random.randint(1000, 10000)

print("Your OTP is:", otp)

Your OTP is: 9053


In [47]:
np.random.randint(10,40,(10,10)) #10x10 matrix between 10 to 40 (here there is no variable)

array([[27, 12, 25, 18, 12, 15, 17, 21, 12, 39],
       [38, 29, 34, 23, 36, 22, 28, 31, 39, 36],
       [19, 20, 18, 17, 32, 26, 29, 15, 23, 16],
       [17, 38, 11, 20, 30, 21, 23, 21, 26, 25],
       [15, 17, 13, 29, 16, 36, 12, 12, 20, 15],
       [25, 38, 30, 28, 34, 18, 14, 20, 14, 16],
       [36, 22, 26, 26, 18, 28, 39, 11, 25, 29],
       [29, 31, 33, 10, 29, 11, 35, 27, 32, 29],
       [11, 14, 28, 36, 25, 27, 18, 39, 31, 26],
       [34, 18, 23, 31, 19, 38, 21, 30, 36, 36]], dtype=int32)

In [48]:
arr1=np.random.randint(10,40,(10,10))     #(we are giving variable and print() so dtype is gone)
print(arr1)

[[26 21 20 22 17 19 31 18 27 27]
 [17 23 26 14 33 12 30 29 21 26]
 [19 11 35 10 19 17 18 13 16 17]
 [34 25 27 11 19 12 29 39 19 11]
 [36 15 33 24 36 31 11 31 29 12]
 [29 37 11 32 28 15 17 11 25 37]
 [12 11 35 16 34 36 32 39 19 29]
 [14 27 18 13 33 34 27 25 27 33]
 [37 31 20 28 23 31 31 21 34 31]
 [34 19 25 21 19 12 38 28 33 28]]


In [50]:
print(arr1)  

[[26 21 20 22 17 19 31 18 27 27]
 [17 23 26 14 33 12 30 29 21 26]
 [19 11 35 10 19 17 18 13 16 17]
 [34 25 27 11 19 12 29 39 19 11]
 [36 15 33 24 36 31 11 31 29 12]
 [29 37 11 32 28 15 17 11 25 37]
 [12 11 35 16 34 36 32 39 19 29]
 [14 27 18 13 33 34 27 25 27 33]
 [37 31 20 28 23 31 31 21 34 31]
 [34 19 25 21 19 12 38 28 33 28]]


In [51]:
arr1[5]     # printing rows from matrix

array([29, 37, 11, 32, 28, 15, 17, 11, 25, 37], dtype=int32)

In [66]:
arr3=np.random.randint(2,4,(5,7))
print(arr3)

[[3 3 3 2 2 2 3]
 [2 3 3 3 2 2 2]
 [3 3 2 3 3 2 3]
 [3 3 3 3 2 3 2]
 [2 2 3 2 2 2 3]]


In [67]:
arr2=np.random.randint(2,9,(5,7))
print(arr2)

[[6 8 8 4 7 6 6]
 [8 3 3 3 6 6 7]
 [4 8 2 6 8 7 2]
 [4 8 7 5 3 6 8]
 [6 7 5 6 6 8 4]]


In [ ]:
# indexing with array

In [68]:
print(arr2)

[[6 8 8 4 7 6 6]
 [8 3 3 3 6 6 7]
 [4 8 2 6 8 7 2]
 [4 8 7 5 3 6 8]
 [6 7 5 6 6 8 4]]


In [69]:
print(arr2[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [70]:
print(arr2[4])

[6 7 5 6 6 8 4]


In [71]:
print(arr2[-3])

[4 8 2 6 8 7 2]


In [72]:
print(arr2[2])    #printing specific row form matrix

[4 8 2 6 8 7 2]


In [ ]:
# slicing with array

In [74]:
arr2

array([[6, 8, 8, 4, 7, 6, 6],
       [8, 3, 3, 3, 6, 6, 7],
       [4, 8, 2, 6, 8, 7, 2],
       [4, 8, 7, 5, 3, 6, 8],
       [6, 7, 5, 6, 6, 8, 4]], dtype=int32)

In [75]:
print(arr2[2:4])

[[4 8 2 6 8 7 2]
 [4 8 7 5 3 6 8]]


In [76]:
print(arr2[2:10])

[[4 8 2 6 8 7 2]
 [4 8 7 5 3 6 8]
 [6 7 5 6 6 8 4]]


In [78]:
print(arr2[:])

[[6 8 8 4 7 6 6]
 [8 3 3 3 6 6 7]
 [4 8 2 6 8 7 2]
 [4 8 7 5 3 6 8]
 [6 7 5 6 6 8 4]]


In [79]:
arr2

array([[6, 8, 8, 4, 7, 6, 6],
       [8, 3, 3, 3, 6, 6, 7],
       [4, 8, 2, 6, 8, 7, 2],
       [4, 8, 7, 5, 3, 6, 8],
       [6, 7, 5, 6, 6, 8, 4]], dtype=int32)

In [80]:
print(arr2[::3])

[[6 8 8 4 7 6 6]
 [4 8 7 5 3 6 8]]


In [85]:
arr2

array([[6, 8, 8, 4, 7, 6, 6],
       [8, 3, 3, 3, 6, 6, 7],
       [4, 8, 2, 6, 8, 7, 2],
       [4, 8, 7, 5, 3, 6, 8],
       [6, 7, 5, 6, 6, 8, 4]], dtype=int32)

In [86]:
arr2[::-1]

array([[6, 7, 5, 6, 6, 8, 4],
       [4, 8, 7, 5, 3, 6, 8],
       [4, 8, 2, 6, 8, 7, 2],
       [8, 3, 3, 3, 6, 6, 7],
       [6, 8, 8, 4, 7, 6, 6]], dtype=int32)

In [87]:
arr2

array([[6, 8, 8, 4, 7, 6, 6],
       [8, 3, 3, 3, 6, 6, 7],
       [4, 8, 2, 6, 8, 7, 2],
       [4, 8, 7, 5, 3, 6, 8],
       [6, 7, 5, 6, 6, 8, 4]], dtype=int32)

In [88]:
arr2[3,4]    #printing speacific value form matrix

np.int32(3)

In [89]:
arr2[4,5]

np.int32(8)

In [90]:
print(arr2[4,5])     #here list is mutable 

8


In [91]:
print(arr2(4,5))        #tuples are immutable

TypeError: 'numpy.ndarray' object is not callable

In [92]:
print(arr2)

[[6 8 8 4 7 6 6]
 [8 3 3 3 6 6 7]
 [4 8 2 6 8 7 2]
 [4 8 7 5 3 6 8]
 [6 7 5 6 6 8 4]]


In [93]:
print(arr2[-3,-3])

8


In [ ]:
# changing the value in matrix

In [94]:
print(arr2[0,1])

8


In [95]:
arr2[0,1]=10

In [101]:
print(arr2)

[[ 6 10  8  4  7  6  6]
 [ 8  3  3  3  6  6  7]
 [ 4  8  2  6  8  7  2]
 [ 4  8  7  5  3  6  8]
 [ 6  7  5  6  6  8  4]]


# to get values of columns

In [102]:
print(arr2[:,0])

[6 8 4 4 6]


In [103]:
print(arr2[:,1])

[10  3  8  8  7]


In [104]:
print(arr2[:,-3])

[7 6 8 3 6]


# printing specific matrix values from matrix

In [105]:
print(arr2)

[[ 6 10  8  4  7  6  6]
 [ 8  3  3  3  6  6  7]
 [ 4  8  2  6  8  7  2]
 [ 4  8  7  5  3  6  8]
 [ 6  7  5  6  6  8  4]]


In [107]:
print(arr2[2:5,2:5])

[[2 6 8]
 [7 5 3]
 [5 6 6]]


In [108]:
print(arr2[1:3,4:])

[[6 6 7]
 [8 7 2]]


# masking or filter in numpy

In [109]:
print(arr2)

[[ 6 10  8  4  7  6  6]
 [ 8  3  3  3  6  6  7]
 [ 4  8  2  6  8  7  2]
 [ 4  8  7  5  3  6  8]
 [ 6  7  5  6  6  8  4]]


In [110]:
arr2<5

array([[False, False, False,  True, False, False, False],
       [False,  True,  True,  True, False, False, False],
       [ True, False,  True, False, False, False,  True],
       [ True, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True]])

In [111]:
arr2[arr2<5]   #filter in numpy

array([4, 3, 3, 3, 4, 2, 2, 4, 3, 4], dtype=int32)

In [112]:
arr2[arr2<=5]

array([4, 3, 3, 3, 4, 2, 2, 4, 5, 3, 5, 4], dtype=int32)

In [113]:
arr2[arr2==5]

array([5, 5], dtype=int32)

In [114]:
arr2[arr2!=5]

array([ 6, 10,  8,  4,  7,  6,  6,  8,  3,  3,  3,  6,  6,  7,  4,  8,  2,
        6,  8,  7,  2,  4,  8,  7,  3,  6,  8,  6,  7,  6,  6,  8,  4],
      dtype=int32)

# reshape

In [115]:
arr

array([0, 1, 2, 3, 4, 5])

In [116]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [117]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [118]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [121]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [122]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [123]:
arr

array([0, 1, 2, 3, 4, 5])

In [124]:
arr.max()

np.int64(5)

In [125]:
arr.min()

np.int64(0)