# 1)Array creation Functions

In [1]:
import numpy as np

In [2]:
#create an array from a list
a=np.array([1,2,3])
print("Array a:",a) # create an array from a list

Array a: [1 2 3]


In [3]:
# create an array with evenly spaced values
b=np.arange(0,10,3)    # values form o to 10 with step 2
print("Array b:",b)

Array b: [0 3 6 9]


In [4]:
#create an array filled with zeros
d=np.zeros((2,3))     #2x3 array of zeros
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#create an array filled with zeros
d=np.zeros((2,3),dtype=int) #2x3 array of zeros
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [6]:
#create an array filled with ones
e=np.ones((3,2)) #3x2 array of ones
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [55]:
#create an array filled with ones
e=np.ones((3,2),dtype=int) #3x2 array of ones
print("Array e:\n",e)

Array e:
 [[1 1]
 [1 1]
 [1 1]]


In [56]:
# create an indentity matrix
f=np.eye(4) #4X4 identity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
f=np.identity(4) #4X4 identity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2)Array Manipulation Functions

In [9]:
# Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3)) # Reshape to 1X3
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [58]:
# Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1)) # Reshape to 3x1
print("Reshaped array:",reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [12]:
# Flatten an array(Manipulating the array)
f1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened=np.ravel(f1)   # flatten to 1D array(we use in computer vision)
print("Flattened array:",flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Transpose an array(convert rows to column ,coulumn to row)
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1) #Transpose the array
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [15]:
#stack arrays vertically
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2]) #stack a and b vertically
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [16]:
#stack arrays horizontal
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2]) #stack a and b horizontally
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [1 2 3 4]


# 3)Math operation in numpy

In [17]:
# Add two arrays
g=np.array([1,2,3,4])
added=np.add(g,2) #Add 2 to each element
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [19]:
# Square each element
squared=np.power(g,2) #Square each element
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [20]:
# Square root of each element
sqrt_val=np.sqrt(g) #Square root of each element
print("Square root of g:",sqrt_val)

Suare root of g: [1.         1.41421356 1.73205081 2.        ]


In [21]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [59]:
a3=np.array([1,2,3])
dot_product=np.dot(a,g) #Dot product of a and g            (dimensions not match),dot product require same dimensions
print("Dot product of a1 and a:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [23]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [25]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a) #Dot product of a1 and a            (dimensions match),dot product require same dimensions
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


# 4)statistical functions

In [26]:
#mean of an array
s=np.array([1,2,3,4])
mean=np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [27]:
# Variance of an array
var=np.var(s)
print("Variance of s:",var)

Variance of s: 1.25


In [28]:
# Standard deviation of  an array
std_dev=np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.118033988749895


In [29]:
s

array([1, 2, 3, 4])

In [30]:
# Minimum element of an array
minimum=np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [31]:
# Maximum element of an array
maximum=np.max(s)
print("Max of s:",maximum)

Max of s: 4


# 5) Linear Algebra Functions

In [61]:
# create a matrix
matrix=np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

# 6) Random sampling 

In [32]:
# Generate random values between 0 and 1
random_vals=np.random.rand(3) #Array of 3 random values between 0 and 1
print("Random values:",random_vals)

Random values: [0.36398709 0.40113796 0.47385482]


In [33]:
# Generate random integers
rand_ints=np.random.randint(0,10,size=4)     #Random integers between 0 and 10
print("Random integers:",rand_ints)

Random integers: [4 2 3 3]


In [53]:
# set seed for reproducibility(once you run the code you wont get another random number,you get same values next time also)
np.random.seed(0) #by default argument(0)
#Generate random integers
rand_ints=np.random.randint(0,10,size=5)     #Random integers between 0 and 10
print("Random integers:",rand_ints)

Random integers: [5 0 3 3 7]


# 7)Boolean and logical functions

In [63]:
#check if all elements are True
#all
logical_test=np.array([True,False,True])
all_true=np.all(logical_test)     #checks if all are True
print("All elements True:",all_true)


All elements True: False


In [64]:
#check if all elements are True
#all
logical_test=np.array([True,True,True])
all_true=np.all(logical_test)     #checks if all are True
print("All elements True:",all_true)

All elements True: True


In [66]:
#check if all elements are True
#all
logical_test=np.array([False,False,False])
all_true=np.all(logical_test)     #checks if all are False
print("All elements True:",all_true)

All elements True: False


In [67]:
#check if all elements are True
#all
logical_test=np.array([False,True,False])
all_true=np.all(logical_test)     #checks if all are False
print("All elements True:",all_true)

All elements True: False


In [68]:
# check if any elements are True
#any
any_true=np.any(logical_test) #check if any are True
print("Any elements True:",any_true)

Any elements True: True


# 8)Set Operations

In [71]:
# Intersection of two arrays
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
intersection=np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [72]:
# union of two arrays
union=np.union1d(set_a,set_b)
print("Union of a and b:",union)

Union of a and b: [1 2 3 4 5 6]


# 9) Array Attribute Functions

In [73]:
# Array attrributes
a=np.array([1,2,3])
shape=a.shape #shape of the array
size=a.size #Number of elements
dimensions=a.ndim #Number of dimensions
dtype=a.dtype #Data type of the array

print("Shape of a:",shape)
print("Size of a:",size)
print("Number of dimensions of a:",dimensions)
print("Data type of a:",dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# 10) other Functions

In [74]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [75]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [77]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
