In [3]:
# What will be the output of the following Python code? 
x = 10 
y = 3.0 
z = x / y 
print(type(z).__name__) 

float


In [4]:
# What will be the output of the following Python code? 
x = 10 
y = x 
x = 20 
print(y)

10


In [5]:
# What will be the output of the following Python code? 
x = 10 
y = 10.0 
print(x == y) 
print(type(x) == type(y)) 

True
False


In [6]:
# What will be the output? 
numbers = [10, 20, 30, 40, 50] 
print(numbers[1:4]) 

[20, 30, 40]


In [7]:
# What will be the output? 
data = [10, 20, 30] 
data.append([40, 50]) 
data.extend([60, 70]) 
print(data) 

[10, 20, 30, [40, 50], 60, 70]


In [8]:
#What will be the output? 
data = {'A': 10, 'B': 20, 'C': 30} 
data['B'] = data['A'] + data['C'] 
print(data['B'])

40


In [9]:
# What will be the output? 
items = [1, 2, 2, 3, 3, 3] 
unique_items = set(items) 
result = tuple(unique_items) 
print(len(result))

3


In [10]:
#What will be the output? 
text = 'Data Science' 
result = text[::2] 
print(result)

Dt cec


In [11]:
#What will be the output? 
numbers = [10, 20, 30, 20, 40] 
print(numbers.count(20)) 

2


In [12]:
#What will be the output? 
student = {'name': 'Rahul', 'age': 22, 'course': 'Data Science'} 
result = student.get('marks', 75) 
print(result) 

75


In [14]:
#What will be the output? 
x = 15 
y = 10 
if x > y: 
    if x % 2 == 0: 
        result = 'Even' 
    else: 
        result = 'Odd' 
else: 
    result = 'Smaller' 
print(result) 

Odd


In [16]:
#What will be the output? 
x = 12 
y = 8 
z = 15 
if x > y and z > x: 
    result = 'A' 
elif x > y or z < y: 
    result = 'B' 
else: 
    result = 'C' 
print(result)

A


In [17]:
#What will be the output? 
 
def calculate(n): 
    if n <= 1: 
        return 1 
    return n + calculate(n - 2) 
 
print(calculate(5))

9


In [18]:
#What will be the output? 
 
num = 121 
reverse = 0 
temp = num 
while temp > 0: 
    digit = temp % 10 
    reverse = reverse * 10 + digit 
    temp //= 10 
if num == reverse: 
    result = 'Palindrome' 
else: 
    result = 'Not Palindrome' 
print(result)

Palindrome


In [19]:
#What will be the output? 
 
num = 29 
is_prime = True 
if num < 2: 
    is_prime = False 
else: 
    for i in range(2, int(num ** 0.5) + 1): 
        if num % i == 0: 
            is_prime = False 
            break 
print('Prime' if is_prime else 'Not Prime')

Prime


In [20]:
#What will be the output? 
 
total = 0 
for i in range(1, 6): 
    if i % 2 == 0: 
        continue 
    total += i 
print(total) 


9


In [21]:
#What will be the output? 
n = 5 
result = 1 
while n > 1: 
    result *= n 
    n -= 2 
print(result) 

15


In [22]:
#What will be the output? 
words = ['python', 'data', 'science', 'ai'] 
result = [] 
for word in words: 
    f = lambda x: x.upper() if len(x) > 4 else x 
    result.append(f(word)) 
print(result)

['PYTHON', 'data', 'SCIENCE', 'ai']


In [23]:
#What will be the output? 
 
text = 'PYTHON' 
result = '' 
for i, ch in enumerate(text): 
    if i % 2 == 0: 
        result += ch.lower() 
    else: 
        result += ch 
print(result) 

pYtHoN


In [24]:
#What will be the output? 
 
number = 12345 
total = 0 
while number > 0: 
    digit = number % 10 
    if digit % 2 != 0: 
        total += digit 
    number //= 10 
print(total)

9


In [25]:
#What will be the output? 
 
marks = {'Python': 78, 'SQL': 85, 'Statistics': 62, 'Machine Learning': 91} 
count = 0 
for subject, mark in marks.items(): 
    if mark >= 80: 
        count += 1 
    elif mark >= 60: 
        count += 0.5 
print(count)

3.0


In [26]:
#What will be the output? 
 
n = 6 
result = 0 
for i in range(1, n + 1): 
    if n % i == 0: 
        result += i 
print(result)

12


In [27]:
#What will be the output? 
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
result = np.sum(arr, axis=0) 
print(result)

[5 7 9]


In [28]:
#What will be the output? 
import numpy as np 
a = np.ones((2, 3)) 
b = np.zeros((2, 3)) 
result = a + b 
print(result) 

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#What will be the output? 
import numpy as np 
arr = np.arange(1, 13) 
result = arr.reshape(3, 4) 
print(result[1:, 1:3]) 